name: arang_pakhsh_app
description: اپلیکیشن سفارش‌گیری شرکت آرنگ پخش نوین کاسپین
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.6.0
  provider: ^6.1.1
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.1.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: BNazanin
      fonts:
        - asset: assets/fonts/B-NAZANIN.TTF
